---
name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SCRIPTS_NO_INTERACTIVE: "true"

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Javascript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: "15"
      - name: Build
        run: |
          npm ci
          npm run ci
          git --no-pager diff && git diff --quiet
      - name: Codecov
        uses: codecov/codecov-action@v1
