---
name: Publish

on:
  push:
    tags:
      - v[0-9]+\.[0-9]+\.[0-9]+
    paths:
      - package.json

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
        run: npm publish
